//* ACTIONS TYPES

//* ADMIN
// export const GET_ADMIN = "GET_ADMIN";
// export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";
// export const GET_ADMIN_FAILURE = "GET_ADMIN_FAILURE";
// export const ADD_ADMIN = "ADD_ADMIN";
// export const ADD_ADMIN_SUCCESS = "ADD_ADMIN_SUCCESS";
// export const ADD_ADMIN_FAILURE = "ADD_ADMIN_FAILURE";
// export const UPDATE_ADMIN = "UPDATE_ADMIN";
// export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
// export const UPDATE_ADMIN_FAILURE = "UPDATE_ADMIN_FAILURE";
// export const DELETE_ADMIN = "DELETE_ADMIN";
// export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
// export const DELETE_ADMIN_FAILURE = "DELETE_ADMIN_FAILURE";
//* USERS
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER = "GET_USER";
export const ADD_NEW_USER = "ADD_NEW_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
//* SERVICES
export const GET_SERVICE = "GET_SERVICE";
export const GET_ALL_SERVICES = "GET_ALL_SERVICES";
export const ADD_NEW_SERVICE = "ADD_NEW_SERVICE";
export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";
// export const SEARCH_BY_SERVICE_NAME = "SEARCH_BY_SERVICE_NAME";
//* CATEGORIES
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
//* ACCESS
export const SET_ACCESS = "SET_ACCESS";